# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        description: trims trailing whitespace.
        entry: .venv/bin/trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: end-of-file-fixer
        name: fix end of files
        description: ensures that a file is either empty, or ends with one newline.
        entry: .venv/bin/end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: debug-statements
        name: debug statements (python)
        description: checks for debugger imports and py37+ `breakpoint()` calls in python source.
        entry: .venv/bin/debug-statement-hook
        language: system
        types: [python]
      - id: check-yaml
        name: check yaml
        description: checks yaml files for parseable syntax.
        entry: .venv/bin/check-yaml
        language: system
        types: [yaml]
      - id: check-added-large-files
        name: check for added large files
        description: prevents giant files from being committed.
        entry: .venv/bin/check-added-large-files
        language: system
        stages: [commit, push, manual]
      - id: check-merge-conflict
        name: check for merge conflicts
        description: checks for files that contain merge conflict strings.
        entry: .venv/bin/check-merge-conflict
        language: system
        types: [text]
      - id: black
        name: black
        description: Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
        entry: .venv/bin/black
        language: system
        types: [python]
        files: ^src/astellas_pj_champion_xta
        exclude: ^src/astellas_pj_champion_xta/pmpx_pkg
      - id: isort
        name: isort
        description: isort your imports for you so you don't have to.
        entry: .venv/bin/isort
        language: system
        types: [python]
        files: ^src/astellas_pj_champion_xta
        exclude: ^src/astellas_pj_champion_xta/pmpx_pkg
        args: ["--profile", "black"]
      - id: flake8
        name: flake8
        description: flake8 is a python tool that glues together pep8, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.
        entry: .venv/bin/flake8
        language: system
        types: [python]
        files: ^src/astellas_pj_champion_xta
        exclude: ^src/astellas_pj_champion_xta/pmpx_pkg
